# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    active:
        label: 'lovata.toolbox::lang.field.active'
        type: switch
        conditions:
            - active <> true
            - active = true
    category:
        label: 'lovata.toolbox::lang.field.category'
        modelClass: Lovata\Shopaholic\Models\Category
        nameFrom: name
        scope: getByCategories
